"""관심분야 추가 user

Revision ID: 16b235b62e05
Revises: 0eae31e3f836
Create Date: 2025-04-10 04:46:05.405444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b235b62e05'
down_revision: Union[str, None] = '0eae31e3f836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('custom_interest', sa.String(), nullable=True))
    op.alter_column('users', 'interests',
                    existing_type=sa.TEXT(),
                    type_=sa.Enum('office', 'service', 'tech', 'education', 'public', 'driver', 'etc',
                                  name='jobinterest_enum'),
                    existing_nullable=True,
                    postgresql_using="interests::jobinterest_enum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'interests',
               existing_type=sa.Enum('office', 'service', 'tech', 'education', 'public', 'driver', 'etc', name='jobinterest_enum'),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('users', 'custom_interest')
    # ### end Alembic commands ###
