"""Update JobPosting model with time, schedule, and duration fields

Revision ID: 1e82b1cdab26
Revises: 72e075a34d11
Create Date: 2025-04-22 09:28:55.284787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e82b1cdab26'
down_revision: Union[str, None] = '72e075a34d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('is_work_duration_negotiable', sa.Boolean(), nullable=True))
    op.add_column('job_postings', sa.Column('is_work_days_negotiable', sa.Boolean(), nullable=True))
    op.add_column('job_postings', sa.Column('is_schedule_based', sa.Boolean(), nullable=True))
    op.add_column('job_postings', sa.Column('work_start_time', sa.String(length=5), nullable=True))
    op.add_column('job_postings', sa.Column('work_end_time', sa.String(length=5), nullable=True))
    op.add_column('job_postings', sa.Column('is_work_time_negotiable', sa.Boolean(), nullable=True))
    op.alter_column('job_postings', 'work_days',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('job_postings', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('job_postings', 'work_days',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('job_postings', 'is_work_time_negotiable')
    op.drop_column('job_postings', 'work_end_time')
    op.drop_column('job_postings', 'work_start_time')
    op.drop_column('job_postings', 'is_schedule_based')
    op.drop_column('job_postings', 'is_work_days_negotiable')
    op.drop_column('job_postings', 'is_work_duration_negotiable')
    # ### end Alembic commands ###
