"""add_is_active_in_company_user

Revision ID: 301a79fa688b
Revises: 6c30e758d08f
Create Date: 2025-04-30 08:35:43.852616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301a79fa688b'
down_revision: Union[str, None] = '6c30e758d08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_users',
                  sa.Column('is_active',
                            sa.Boolean(),
                            nullable=False,
                            server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_users', 'is_active')
    # ### end Alembic commands ###
