"""company model 추가

Revision ID: 521c9ce70bd8
Revises: 97f1682c96f6
Create Date: 2025-04-09 06:59:24.983280

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "521c9ce70bd8"
down_revision: Union[str, None] = "97f1682c96f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_name", sa.String(length=50), nullable=False),
        sa.Column("business_reg_number", sa.String(length=50), nullable=False),
        sa.Column("opening_date", sa.Date(), nullable=False),
        sa.Column("company_intro", sa.Text(), nullable=False),
        sa.Column("ceo_name", sa.String(length=50), nullable=False),
        sa.Column("address", sa.String(length=100), nullable=True),
        sa.Column("company_image", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_reg_number"),
    )
    op.create_index(op.f("ix_company_info_id"), "company_info", ["id"], unique=False)
    op.create_table(
        "company_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("manager_name", sa.String(length=50), nullable=False),
        sa.Column("manager_phone", sa.String(length=20), nullable=False),
        sa.Column("manager_email", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_company_users_email"), "company_users", ["email"], unique=True
    )
    op.create_index(op.f("ix_company_users_id"), "company_users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_company_users_id"), table_name="company_users")
    op.drop_index(op.f("ix_company_users_email"), table_name="company_users")
    op.drop_table("company_users")
    op.drop_index(op.f("ix_company_info_id"), table_name="company_info")
    op.drop_table("company_info")
    # ### end Alembic commands ###
