"""Sync work_duration_enum values

Revision ID: 872be4f1344a
Revises: 1e82b1cdab26
Create Date: 2025-04-23 04:53:23.632157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872be4f1344a'
down_revision: Union[str, None] = '1e82b1cdab26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. PostgreSQL ENUM 타입에 누락된 값 추가
    op.execute("ALTER TYPE work_duration_enum ADD VALUE IF NOT EXISTS 'between_3_6_months' AFTER 'more_3_months'")
    op.execute("ALTER TYPE work_duration_enum ADD VALUE IF NOT EXISTS 'between_6_12_months' AFTER 'more_6_months'")
    op.execute("ALTER TYPE work_duration_enum ADD VALUE IF NOT EXISTS 'between_1_3_years' AFTER 'more_1_year'")

    # 2. 'negotiable' 값 제거 (매우 주의! 적용 전 데이터 확인 및 백업 필수!)
    #    기존 데이터 중 'negotiable'을 사용하는 행이 없는지 반드시 확인하고,
    #    있다면 다른 값으로 변경한 후 이 마이그레이션을 적용해야 합니다.
    op.execute("ALTER TYPE work_duration_enum RENAME TO work_duration_enum_old")
    op.execute("CREATE TYPE work_duration_enum AS ENUM ('more_3_months', 'between_3_6_months', 'more_6_months', 'between_6_12_months', 'more_1_year', 'between_1_3_years', 'more_3_years')")
    op.execute("ALTER TABLE job_postings ALTER COLUMN work_duration TYPE work_duration_enum USING work_duration::text::work_duration_enum")
    op.execute("DROP TYPE work_duration_enum_old")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ENUM 값 추가/제거 작업은 복잡하고 데이터 유실 위험이 있어
    # downgrade를 자동으로 구현하기 어렵습니다. 필요 시 수동으로 복구해야 합니다.
    pass
    # ### end Alembic commands ###
