"""add users, resumes, resumes_education models

Revision ID: 9a42a78b1912
Revises: 52a275010cc1
Create Date: 2025-04-09 08:38:58.728569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a42a78b1912'
down_revision: Union[str, None] = '52a275010cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    gender_enum = postgresql.ENUM('남성', '여성', name='genderenum')
    gender_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'users',
        sa.Column(
            'gender',
            gender_enum,
            nullable=True
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_image', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('work_period_start', sa.Date(), nullable=True),
    sa.Column('work_period_end', sa.Date(), nullable=True),
    sa.Column('desired_area', sa.String(length=255), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_table('resumes_educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resumes_id', sa.Integer(), nullable=False),
    sa.Column('education_type', sa.Enum('high_school', 'college_2_3', 'college_4', 'graduate', name='educationtype'), nullable=True),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('education_status', sa.Enum('graduated', 'studying', 'on_leave', 'expected', name='educationstatus'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resumes_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_educations_id'), 'resumes_educations', ['id'], unique=False)
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('user_image', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('interests', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('signup_purpose', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('referral_source', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'referral_source')
    op.drop_column('users', 'signup_purpose')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'user_image')
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_resumes_educations_id'), table_name='resumes_educations')
    op.drop_table('resumes_educations')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
