"""Add region1 and region2 columns to job_postings table

Revision ID: ace058fb34d7
Revises: ecaacccf1cd8
Create Date: 2025-05-02 02:23:40.920561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace058fb34d7'
down_revision: Union[str, None] = 'ecaacccf1cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('region1', sa.String(length=50), nullable=True))
    op.add_column('job_postings', sa.Column('region2', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'region2')
    op.drop_column('job_postings', 'region1')
    # ### end Alembic commands ###
