"""model change

Revision ID: ad3647d24df2
Revises: e370f0478bcd
Create Date: 2025-04-17 07:39:51.410796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3647d24df2'
down_revision: Union[str, None] = 'e370f0478bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_info', 'opening_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_info', 'opening_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
