"""Add NOT NULL and ON DELETE CASCADE to job_postings foreign keys

Revision ID: af280a57e942
Revises: ace058fb34d7
Create Date: 2025-05-06 03:13:05.761615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af280a57e942'
down_revision: Union[str, None] = 'ace058fb34d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_postings', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('job_postings_company_id_fkey', 'job_postings', type_='foreignkey')
    op.drop_constraint('job_postings_author_id_fkey', 'job_postings', type_='foreignkey')
    op.create_foreign_key(None, 'job_postings', 'company_users', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'job_postings', 'company_info', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.create_foreign_key('job_postings_author_id_fkey', 'job_postings', 'company_users', ['author_id'], ['id'])
    op.create_foreign_key('job_postings_company_id_fkey', 'job_postings', 'company_info', ['company_id'], ['id'])
    op.alter_column('job_postings', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_postings', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
