"""delete deadline_at

Revision ID: bf9ad984956a
Revises: d3eb1965e8a9
Create Date: 2025-04-18 09:57:06.992923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf9ad984956a'
down_revision: Union[str, None] = 'd3eb1965e8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_info', sa.Column('manager_name', sa.String(length=50), nullable=False, server_default='없음'))
    op.add_column('company_info', sa.Column('manager_phone', sa.String(length=20), nullable=False, server_default='없음'))
    op.add_column('company_info', sa.Column('manager_email', sa.String(length=100), nullable=True))
    op.drop_column('company_users', 'manager_phone')
    op.drop_column('company_users', 'manager_email')
    op.drop_column('company_users', 'manager_name')
    op.drop_column('job_postings', 'deadline_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('deadline_at', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('company_users', sa.Column('manager_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('company_users', sa.Column('manager_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('company_users', sa.Column('manager_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('company_info', 'manager_email')
    op.drop_column('company_info', 'manager_phone')
    op.drop_column('company_info', 'manager_name')
    # ### end Alembic commands ###
