"""model change

Revision ID: d3eb1965e8a9
Revises: ad3647d24df2
Create Date: 2025-04-18 05:27:11.150792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3eb1965e8a9'
down_revision: Union[str, None] = 'ad3647d24df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('resume_id', sa.Integer(), nullable=False))
    op.add_column('job_applications', sa.Column('resumes_data', sa.JSON(), nullable=False, comment='지원 시점 이력서 데이터 스냅샷'))
    op.drop_constraint('uq_user_jobposting', 'job_applications', type_='unique')
    op.create_unique_constraint('uq_resume_jobposting', 'job_applications', ['resume_id', 'job_posting_id'])
    op.create_foreign_key(None, 'job_applications', 'resumes', ['resume_id'], ['id'])
    op.drop_column('resumes', 'position')
    op.drop_column('resumes', 'work_period_start')
    op.drop_column('resumes', 'company_name')
    op.drop_column('resumes', 'work_period_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('work_period_end', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('work_period_start', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('position', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.drop_constraint('uq_resume_jobposting', 'job_applications', type_='unique')
    op.create_unique_constraint('uq_user_jobposting', 'job_applications', ['user_id', 'job_posting_id'])
    op.drop_column('job_applications', 'resumes_data')
    op.drop_column('job_applications', 'resume_id')
    # ### end Alembic commands ###
