"""user_type 생성

Revision ID: ecaacccf1cd8
Revises: 19191bf3438c
Create Date: 2025-04-30 16:28:38.906743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecaacccf1cd8'
down_revision: Union[str, None] = '19191bf3438c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verifications', sa.Column('user_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_verifications', 'user_type')
    # ### end Alembic commands ###
